service: emailgate-functions

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: us-east-1

functions:
  emailPdf:
    handler: functions/emailPdf/emailPdf.default
    events:
      - http:
          path: emails/{id}/pdf
          method: post
    environment:
      MONGO_URL: ${file(./env.yml):MONGO_URL}
      MANTA_APP_KEY: ${file(./env.yml):MANTA_APP_KEY}
      MANTA_APP_KEY_ID: ${file(./env.yml):MANTA_APP_KEY_ID}
      MANTA_APP_USER: ${file(./env.yml):MANTA_APP_USER}
      MANTA_APP_USER_ID: ${file(./env.yml):MANTA_APP_USER_ID}
      MANTA_APP_URL: ${file(./env.yml):MANTA_APP_URL}
      MANTA_APP_PUBLIC_PATH: ${file(./env.yml):MANTA_APP_PUBLIC_PATH}
